[package]
name = "tof-control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i2cdev = "0.5.1"
memmap = "0.7"
log = "0.4"
clap = { version = "4.1", features = ["derive"] }
csv = "1.1"