[package]
name = "tof-control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"

[[bin]]
name = "i2c-check"
path = "src/bin/i2c_check.rs"

[[bin]]
name = "rb-watchdog"
path = "src/bin/rb_watchdog.rs"

[[bin]]
name = "dac-test"
path = "src/bin/dac_test.rs"

[dependencies]
i2cdev = "0.5.1"
memmap = "0.7"
log = "0.4"
clap = { version = "4.1", features = ["derive"] }
csv = "1.1"